# ***`CREDIT CARD FRAUD DETECTION PROJECT`***

---



# **2.   USING LOGISTIC REGRESSION**

In [ ]:
import numpy as np
import pandas as pd
credit_df=pd.read_csv('/content/drive/MyDrive/DATASETS/creditcard.csv')

In [ ]:
credit_df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [ ]:
X=credit_df.drop(['Time','Amount','Class'],axis=1)
Y=credit_df['Class']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)
print('Training Data',X_train)
print('Testing Data',X_test)
print('Training Data y',y_train)
print('Testing Data y',y_test)

Training Data               V1        V2        V3        V4        V5        V6        V7  \
252956 -3.692348  3.008841 -1.121494 -0.778320 -2.538427 -0.310044 -1.727557   
194309 -0.964199  1.136658  0.759537 -0.800651  0.834249 -0.778122  1.105079   
270255 -0.966559  1.591731  1.354527  4.026130  0.678443  3.500128 -0.608266   
223988  0.066637  0.059921  0.374792 -1.822184  0.119898 -0.979894 -1.120815   
138234 -1.791995  1.102738  0.324217  1.082267 -0.303348 -1.050303  0.066270   
...          ...       ...       ...       ...       ...       ...       ...   
166007 -0.283448  0.476786  0.542444 -0.538995  0.560207 -0.401176  0.951885   
184180  0.174922  0.380976  0.451971 -0.442832  0.381610 -0.678288  1.174274   
71115   0.896775 -2.084531  0.101396 -1.272601 -1.828544 -0.404359 -0.760011   
19996   1.172969  0.221508  0.622677  0.650761 -0.406620 -0.690456  0.049612   
275761 -6.012311  3.172411 -1.894695  0.750444 -2.586855 -0.201284 -2.642647   

              V8        V

In [ ]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()
logreg.fit(X_train,y_train)

LogisticRegression()

In [ ]:
y_predict=logreg.predict(X_test)
y_predict

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
pd.DataFrame({'Actual':y_test,'Predicted':y_predict})

Actual  Predicted
250435       0          0
88337        0          0
191209       0          0
179001       0          0
253768       0          0
...        ...        ...
211773       0          0
104080       0          0
222355       0          0
149266       0          0
117057       0          0

[56962 rows x 2 columns]

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict, target_names=['FAKE','AUTHENTIC']))

[[56864     8]
 [   31    59]]
              precision    recall  f1-score   support

        FAKE       1.00      1.00      1.00     56872
   AUTHENTIC       0.88      0.66      0.75        90

    accuracy                           1.00     56962
   macro avg       0.94      0.83      0.88     56962
weighted avg       1.00      1.00      1.00     56962



In [ ]:
df1=pd.read_csv('/content/drive/MyDrive/DATASETS/CC.csv', index_col=0)
df1=df1.drop(['Time','Amount','Class'],axis=1)
print(df1)
y_pred=classifier.predict(df1)

               V1         V2        V3        V4        V5        V6  \
1       -1.359807  -0.072781  2.536347  1.378155 -0.338321  0.462388   
2        1.191857   0.266151  0.166480  0.448154  0.060018 -0.082361   
3       -1.358354  -1.340163  1.773209  0.379780 -0.503198  1.800499   
4       -0.966272  -0.185226  1.792993 -0.863291 -0.010309  1.247203   
5       -1.158233   0.877737  1.548718  0.403034 -0.407193  0.095921   
...           ...        ...       ...       ...       ...       ...   
284803 -11.881118  10.071785 -9.834783 -2.066656 -5.364473 -2.606837   
284804  -0.732789  -0.055080  2.035030 -0.738589  0.868229  1.058415   
284805   1.919565  -0.301254 -3.249640 -0.557828  2.630515  3.031260   
284806  -0.240440   0.530483  0.702510  0.689799 -0.377961  0.623708   
284807  -0.533413  -0.189733  0.703337 -0.506271 -0.012546 -0.649617   

              V7        V8        V9       V10  ...       V19       V20  \
1       0.239599  0.098698  0.363787  0.090794  ...  0.40399

In [ ]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
df_list=[]
for i in y_pred:
  if i==0:
    temp_df = pd.DataFrame({'Authenticity': ['Fake']})
  else:
    temp_df = pd.DataFrame({'Authenticity': ['Real']})
  df_list.append(temp_df)
df1=pd.concat(df_list,ignore_index=True)

In [ ]:
df1

Authenticity
0              Fake
1              Fake
2              Fake
3              Fake
4              Fake
...             ...
284802         Fake
284803         Fake
284804         Fake
284805         Fake
284806         Fake

[284807 rows x 1 columns]

# **FINDS AUTHENTIC CREDIT CARDS**

In [ ]:
df1[df1['Authenticity']=='Real']

Authenticity
541            Real
623            Real
4920           Real
5171           Real
6108           Real
...             ...
279863         Real
280143         Real
280149         Real
281144         Real
281674         Real

[493 rows x 1 columns]

In [ ]:
df2=pd.read_csv('/content/drive/MyDrive/DATASETS/CC.csv',index_col=0)
df2

Time         V1         V2        V3        V4        V5  \
1            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
2            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
3            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
4            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
5            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284803  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284804  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284805  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284806  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284807  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
1       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
2      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
3       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
4       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
5       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284803 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284804  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284805  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284806  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284807 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
1      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
2       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
3       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
4      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
5      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284803  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284804  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284805 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284806 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284807  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
1           0  
2           0  
3           0  
4           0  
5           0  
...       ...  
284803      0  
284804      0  
284805      0  
284806      0  
284807      0  

[284807 rows x 31 columns]

In [ ]:
df1.reset_index(drop=True, inplace=True)
df2.reset_index(drop=True, inplace=True)
df2=pd.concat([df2,df1],axis=1)


In [ ]:
df2

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V22       V23  \
0       0.462388  0.239599  0.098698  0.363787  ...  0.277838 -0.110474   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.638672  0.101288   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.771679  0.909412   
3       1.247203  0.237609  0.377436 -1.387024  ...  0.005274 -0.190321   
4       0.095921  0.592941 -0.270533  0.817739  ...  0.798278 -0.137458   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.111864  1.014480   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.924384  0.012463   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.578229 -0.037501   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.800049 -0.163298   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.643078  0.376777   

             V24       V25       V26       V27       V28  Amount  Class  \
0       0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62      0   
1      -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69      0   
2      -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0   
3      -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50      0   
4       0.141267 -0.206010  0.502292  0.219422  0.215153   69.99      0   
...          ...       ...       ...       ...       ...     ...    ...   
284802 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77      0   
284803 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79      0   
284804  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88      0   
284805  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00      0   
284806  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00      0   

        Authenticity  
0               Fake  
1               Fake  
2               Fake  
3               Fake  
4               Fake  
...              ...  
284802          Fake  
284803          Fake  
284804          Fake  
284805          Fake  
284806          Fake  

[284807 rows x 32 columns]

In [ ]:
df2.to_csv('/content/drive/MyDrive/DATASETS/CC.csv')