# ***`CREDIT CARD FRAUD DETECTION PROJECT`***

---





#**1.   USING DECISION TREE**






In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
credit=pd.read_csv('/content/drive/MyDrive/DATASETS/creditcard.csv')
credit

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [ ]:
X=credit.drop(['Class','Amount','Time'], axis=1)
Y=credit['Class']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)
print('Training Data',X_train)
print('Testing Data',X_test)
print('Training Data y',y_train)
print('Testing Data y',y_test)

Training Data               V1        V2        V3        V4        V5        V6        V7  \
218375  0.095825  0.869604  0.011025 -0.750683  0.767399 -0.726437  1.009362   
69774  -0.604237  1.225626  0.882227  0.946374 -0.310060 -0.743293  0.610900   
55891   0.319748 -1.544982  0.831751  1.005981 -0.845023  1.695313 -0.537292   
255266 -1.337355 -1.005519 -2.571016 -1.885885  1.244514 -2.744724  1.607383   
205468 -1.257380  0.148427  1.122478 -3.364173 -0.605994 -0.621323 -0.105895   
...          ...       ...       ...       ...       ...       ...       ...   
202900 -0.491873  1.356494 -0.751957  0.651015  1.242345  0.153067  0.777299   
195505 -0.601666  0.360018 -0.047917 -0.635793  0.947430 -0.715207  0.888914   
174159  1.929025  0.626157 -0.970011  3.604050  0.771009  0.036124  0.317972   
155751  1.873928 -0.432011 -0.511812  0.132338  0.212997  1.308348 -0.961770   
187144  1.867120 -0.780505 -0.783968  0.051674 -0.433185  0.094086 -0.626569   

              V8        V

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred=classifier.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred, target_names=['FAKE','AUTHENTIC']))

[[56864    23]
 [   22    53]]
              precision    recall  f1-score   support

        FAKE       1.00      1.00      1.00     56887
   AUTHENTIC       0.70      0.71      0.70        75

    accuracy                           1.00     56962
   macro avg       0.85      0.85      0.85     56962
weighted avg       1.00      1.00      1.00     56962



In [ ]:
y_pred=classifier.predict([[-1.3598071336738,-0.0727811733098497,2.53634673796914,1.37815522427443,-0.338320769942518,0.462387777762292,0.239598554061257,0.0986979012610507,0.363786969611213,
                            0.0907941719789316,-0.551599533260813,-0.617800855762348,-0.991389847235408,-0.311169353699879,1.46817697209427,-0.470400525259478,0.207971241929242,0.0257905801985591,
                            0.403992960255733,0.251412098239705,-0.018306777944153,0.277837575558899,-0.110473910188767,0.0669280749146731,0.128539358273528,-0.189114843888824,0.133558376740387,
                            -0.0210530534538215]])
print(y_pred)

[0]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [ ]:
import pandas as pd
df1=pd.read_csv('/content/drive/MyDrive/DATASETS/CC.csv', index_col=0)
df1.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
1   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
2   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
3   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
4   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
5   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
1  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
2  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
3  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
4  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
5 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
1 -0.189115  0.133558 -0.021053  149.62      0  
2  0.125895 -0.008983  0.014724    2.69      0  
3 -0.139097 -0.055353 -0.059752  378.66      0  
4 -0.221929  0.062723  0.061458  123.50      0  
5  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [ ]:
df1=df1.drop(['Time','Amount','Class'],axis=1)
df1.head()

V1        V2        V3        V4        V5        V6        V7  \
1 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
2  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
3 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
4 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
5 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V19       V20       V21       V22  \
1  0.098698  0.363787  0.090794  ...  0.403993  0.251412 -0.018307  0.277838   
2  0.085102 -0.255425 -0.166974  ... -0.145783 -0.069083 -0.225775 -0.638672   
3  0.247676 -1.514654  0.207643  ... -2.261857  0.524980  0.247998  0.771679   
4  0.377436 -1.387024 -0.054952  ... -1.232622 -0.208038 -0.108300  0.005274   
5 -0.270533  0.817739  0.753074  ...  0.803487  0.408542 -0.009431  0.798278   

        V23       V24       V25       V26       V27       V28  
1 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  
2  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724  
3  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  
4 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  
5 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153  

[5 rows x 28 columns]

In [ ]:
df1=df1.to_numpy()
df1

array([[-1.35980713e+00, -7.27811733e-02,  2.53634674e+00, ...,
        -1.89114844e-01,  1.33558377e-01, -2.10530535e-02],
       [ 1.19185711e+00,  2.66150712e-01,  1.66480113e-01, ...,
         1.25894532e-01, -8.98309914e-03,  1.47241692e-02],
       [-1.35835406e+00, -1.34016307e+00,  1.77320934e+00, ...,
        -1.39096572e-01, -5.53527940e-02, -5.97518406e-02],
       ...,
       [ 1.91956501e+00, -3.01253846e-01, -3.24963981e+00, ...,
        -8.73705959e-02,  4.45477214e-03, -2.65608286e-02],
       [-2.40440050e-01,  5.30482513e-01,  7.02510230e-01, ...,
         5.46668462e-01,  1.08820735e-01,  1.04532821e-01],
       [-5.33412522e-01, -1.89733337e-01,  7.03337367e-01, ...,
        -8.18267121e-01, -2.41530880e-03,  1.36489143e-02]])

In [ ]:
y_pred=classifier.predict(df1)
print(y_pred)

[0 0 0 ... 0 0 0]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


# **FINDS AUTHENTIC CREDIT CARDS**

In [ ]:
import numpy as np
np.where(y_pred == 1)

(array([   541,    623,   4920,   5171,   6108,   6329,   6331,   6334,
          6336,   6338,   6427,   6446,   6472,   6529,   6609,   6641,
          6717,   6719,   6734,   6774,   6820,   6870,   6882,   6899,
          6903,   6971,   8296,   8312,   8335,   8615,   8617,   8842,
          8845,   8972,   9035,   9179,   9252,   9487,   9509,  10204,
         10484,  10497,  10498,  10568,  10630,  10690,  10801,  10891,
         10897,  11343,  11710,  11841,  11880,  12070,  12108,  12261,
         12369,  14170,  14197,  14211,  15166,  15204,  15225,  15321,
         15451,  15476,  15506,  15539,  15566,  15736,  15751,  15781,
         15810,  16415,  16780,  16863,  17317,  17366,  17407,  17453,
         17480,  18466,  18472,  18773,  18809,  20198,  23308,  23422,
         24520,  27359,  27362,  27627,  27738,  27749,  29687,  30100,
         30314,  30384,  30398,  30442,  30473,  30496,  31002,  33276,
         40085,  40525,  41395,  41569,  41943,  42007,  42009, 